name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Ou 'master' dependendo do seu repositório

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Deploy no GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out  # Pasta padrão do Next.js export
          clean: true
