name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Alterar se sua branch principal tiver outro nome

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências (Ignorando conflitos)
        run: npm install --legacy-peer-deps

      - name: Build e Exportar
        run: |
          npm run build
          npm run export

      - name: Deploy no GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Branch onde os arquivos estáticos serão publicados
          folder: out  # Pasta gerada pelo export do Next.js
